apiVersion: v1
kind: Service
metadata:
  name: {{ include "city-helm.fullname" . }}
  labels:
    {{- include "city-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
      nodePort: 30003
  selector:
    {{- include "city-helm.selectorLabels" . | nindent 4 }}
